In [1]:
import pandas as pd
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
%matplotlib inline
matplotlib.rcParams['figure.figsize'] = (12,8)

In [2]:
df = pd.read_csv('C:\\Users\\drbhi\\venv\\CSCN8000_classic_ml\\Book_Dataset.csv')
df

,title,author,price,avg_reviews
0,Becoming a Data Head: How to Think Speak and U...,"[Alex J. Gutman,Jordan Goldmeier]",24.49,4.6
1,Ace the Data Science Interview: 201 Real Inter...,"[Nick Singh,Kevin Huo]",26.00,4.5
2,Fundamentals of Data Engineering: Plan and Bui...,"[Joe Reis,Matt Housley]",50.76,5.0
3,Essential Math for Data Science: Take Control ...,[Thomas Nield],44.80,4.5
4,Data Science for Business: What You Need to Kn...,"[Foster Provost,Tom Fawcett]",36.99,4.5
...,...,...,...,...
941,The Book of R: A First Course in Programming a...,[Tilman M. Davies],28.33,4.6
942,Basic Business Statistics: A Casebook (Textboo...,"[Dean P. Foster,Robert A. Stine et al.]",59.23,4.3
943,Elementary Statistics: Picturing the World,"[Ron Larson,Betsy Farber]",129.99,4.5
944,Making Sense of Statistics: A Conceptual Overview,"[Fred Pyrczak,Deborah M. Oh]",47.76,4.6
945,Psychology Statistics For Dummies,"[Donncha Hanna,Martin Dempster]",15.55,4.5

In [3]:
df.head()

,title,author,price,avg_reviews
0,Becoming a Data Head: How to Think Speak and U...,"[Alex J. Gutman,Jordan Goldmeier]",24.49,4.6
1,Ace the Data Science Interview: 201 Real Inter...,"[Nick Singh,Kevin Huo]",26.00,4.5
2,Fundamentals of Data Engineering: Plan and Bui...,"[Joe Reis,Matt Housley]",50.76,5.0
3,Essential Math for Data Science: Take Control ...,[Thomas Nield],44.80,4.5
4,Data Science for Business: What You Need to Kn...,"[Foster Provost,Tom Fawcett]",36.99,4.5

In [4]:
df.price.describe()

count     944.000000
mean       56.023019
std        95.544123
min         4.730000
25%        31.982500
50%        44.185000
75%        56.990000
max      2451.690000
Name: price, dtype: float64

In [5]:
df.price.quantile(0)

4.73

In [6]:
df.price.quantile(0.25,interpolation="higher")

31.99

In [7]:
df.price.quantile(0.25,interpolation="lower")

31.96

In [8]:
df.price.quantile(0.75,interpolation="lower")

56.99

In [9]:
df.price.quantile(1)

2451.69

In [10]:
z= df.price.quantile(0.99,interpolation="lower")

In [11]:
z

197.32

In [12]:
df[df.price>z]

,title,author,price,avg_reviews
248,Computational Topology for Biomedical Image an...,NaN,1318.36,NaN
254,Cluster Analysis 5th Edition,[Everitt],2451.69,4.2
441,Adversarial Deep Learning in Cybersecurity: At...,"[Aneesh Sreevallabh Chivukula,Xinghao Yang et ...",199.99,NaN
850,Statistics for Business and Economics,"[James McClave,P. George Benson et al.]",223.99,4.3
861,First Course in Probability A,[Sheldon Ross],215.32,4.2
867,Introduction to the Practice of Statistics,"[David S. Moore,George P. McCabe et al.]",240.34,3.6
885,Using SPSS for Windows and Macintosh (7th Edit...,"[Samuel B. Green,Neil J. Salkind]",279.95,4.4
917,Statistics,"[James McClave,Terry Sincich]",253.32,4.3
920,Statistics for Business: Decision Making and A...,"[Robert Stine,Dean Foster]",223.98,4.5

In [13]:
df['price'][1]=np.NaN

C:\Users\drbhi\AppData\Local\Temp\ipykernel_1420\4193790169.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price'][1]=np.NaN

In [14]:
df

,title,author,price,avg_reviews
0,Becoming a Data Head: How to Think Speak and U...,"[Alex J. Gutman,Jordan Goldmeier]",24.49,4.6
1,Ace the Data Science Interview: 201 Real Inter...,"[Nick Singh,Kevin Huo]",NaN,4.5
2,Fundamentals of Data Engineering: Plan and Bui...,"[Joe Reis,Matt Housley]",50.76,5.0
3,Essential Math for Data Science: Take Control ...,[Thomas Nield],44.80,4.5
4,Data Science for Business: What You Need to Kn...,"[Foster Provost,Tom Fawcett]",36.99,4.5
...,...,...,...,...
941,The Book of R: A First Course in Programming a...,[Tilman M. Davies],28.33,4.6
942,Basic Business Statistics: A Casebook (Textboo...,"[Dean P. Foster,Robert A. Stine et al.]",59.23,4.3
943,Elementary Statistics: Picturing the World,"[Ron Larson,Betsy Farber]",129.99,4.5
944,Making Sense of Statistics: A Conceptual Overview,"[Fred Pyrczak,Deborah M. Oh]",47.76,4.6
945,Psychology Statistics For Dummies,"[Donncha Hanna,Martin Dempster]",15.55,4.5

In [15]:
df.price.mean()

56.05485683987274

Handling Missing Values:

In [16]:
df_new_price = df.fillna(df.price.mean())
df_new_price

,title,author,price,avg_reviews
0,Becoming a Data Head: How to Think Speak and U...,"[Alex J. Gutman,Jordan Goldmeier]",24.490000,4.6
1,Ace the Data Science Interview: 201 Real Inter...,"[Nick Singh,Kevin Huo]",56.054857,4.5
2,Fundamentals of Data Engineering: Plan and Bui...,"[Joe Reis,Matt Housley]",50.760000,5.0
3,Essential Math for Data Science: Take Control ...,[Thomas Nield],44.800000,4.5
4,Data Science for Business: What You Need to Kn...,"[Foster Provost,Tom Fawcett]",36.990000,4.5
...,...,...,...,...
941,The Book of R: A First Course in Programming a...,[Tilman M. Davies],28.330000,4.6
942,Basic Business Statistics: A Casebook (Textboo...,"[Dean P. Foster,Robert A. Stine et al.]",59.230000,4.3
943,Elementary Statistics: Picturing the World,"[Ron Larson,Betsy Farber]",129.990000,4.5
944,Making Sense of Statistics: A Conceptual Overview,"[Fred Pyrczak,Deborah M. Oh]",47.760000,4.6
945,Psychology Statistics For Dummies,"[Donncha Hanna,Martin Dempster]",15.550000,4.5

In [17]:
df_new_price_data = df.fillna(df.price.median())
df_new_price_data

,title,author,price,avg_reviews
0,Becoming a Data Head: How to Think Speak and U...,"[Alex J. Gutman,Jordan Goldmeier]",24.49,4.6
1,Ace the Data Science Interview: 201 Real Inter...,"[Nick Singh,Kevin Huo]",44.37,4.5
2,Fundamentals of Data Engineering: Plan and Bui...,"[Joe Reis,Matt Housley]",50.76,5.0
3,Essential Math for Data Science: Take Control ...,[Thomas Nield],44.80,4.5
4,Data Science for Business: What You Need to Kn...,"[Foster Provost,Tom Fawcett]",36.99,4.5
...,...,...,...,...
941,The Book of R: A First Course in Programming a...,[Tilman M. Davies],28.33,4.6
942,Basic Business Statistics: A Casebook (Textboo...,"[Dean P. Foster,Robert A. Stine et al.]",59.23,4.3
943,Elementary Statistics: Picturing the World,"[Ron Larson,Betsy Farber]",129.99,4.5
944,Making Sense of Statistics: A Conceptual Overview,"[Fred Pyrczak,Deborah M. Oh]",47.76,4.6
945,Psychology Statistics For Dummies,"[Donncha Hanna,Martin Dempster]",15.55,4.5

In [18]:
df_new_price_data

,title,author,price,avg_reviews
0,Becoming a Data Head: How to Think Speak and U...,"[Alex J. Gutman,Jordan Goldmeier]",24.49,4.6
1,Ace the Data Science Interview: 201 Real Inter...,"[Nick Singh,Kevin Huo]",44.37,4.5
2,Fundamentals of Data Engineering: Plan and Bui...,"[Joe Reis,Matt Housley]",50.76,5.0
3,Essential Math for Data Science: Take Control ...,[Thomas Nield],44.80,4.5
4,Data Science for Business: What You Need to Kn...,"[Foster Provost,Tom Fawcett]",36.99,4.5
...,...,...,...,...
941,The Book of R: A First Course in Programming a...,[Tilman M. Davies],28.33,4.6
942,Basic Business Statistics: A Casebook (Textboo...,"[Dean P. Foster,Robert A. Stine et al.]",59.23,4.3
943,Elementary Statistics: Picturing the World,"[Ron Larson,Betsy Farber]",129.99,4.5
944,Making Sense of Statistics: A Conceptual Overview,"[Fred Pyrczak,Deborah M. Oh]",47.76,4.6
945,Psychology Statistics For Dummies,"[Donncha Hanna,Martin Dempster]",15.55,4.5

(1) Outlier detection and removal using Standard Deviation

In [19]:
min_limit, max_limit = df.price.quantile([0.0001, 0.999])
min_limit, max_limit

(5.100206, 1384.0931400001205)

In [20]:
df[df.price<min_limit]

,title,author,price,avg_reviews
51,Bootstrap:Data Science Workbook,"[Emmanuel Schanzer,Kathi Fisler et al.]",4.73,NaN

In [21]:
outliers = df[(df.price>max_limit) | (df.price<min_limit)]
outliers

,title,author,price,avg_reviews
51,Bootstrap:Data Science Workbook,"[Emmanuel Schanzer,Kathi Fisler et al.]",4.73,NaN
254,Cluster Analysis 5th Edition,[Everitt],2451.69,4.2